name: ':bug: Bug Report'
description: 'Create a bug report'
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: 'checkboxes'
    attributes:
      label: 'Version Check'
      options:
        - label: 'This is the latest version of Viewer.'
          required: true
        - label: 'NET Framework v4.8 or(and) v4.8.1 is installed on my computer.'
          required: true
  - type: 'input'
    attributes:
      label: 'Version'
      description: 'Please enter the viewer version used.'
      placeholder: 'ex: 1.0.0'
    validations:
      required: true
  - type: 'textarea'
    attributes:
      label: 'Description'
      description: 'Please fill in the description of the bug.'
    validations:
      required: true
  - type: 'textarea'
    attributes:
      label: 'Environment'
      description: 'Please enter the your OS information.'
      placeholder:  |
        * Windows 11 24H2 26100.3323
        * x64
    validations:
      required: true
