//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FkgNewsViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FkgNewsViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fkg News Viewer.
        /// </summary>
        public static string PRODUCT_NAME {
            get {
                return ResourceManager.GetString("PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string TAB_PRINT {
            get {
                return ResourceManager.GetString("TAB_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect.
        /// </summary>
        public static string TAB_REDIRECT {
            get {
                return ResourceManager.GetString("TAB_REDIRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string TAB_RELOAD {
            get {
                return ResourceManager.GetString("TAB_RELOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input must be integer within the range: .
        /// </summary>
        public static string WIN_PAGE_MAIN_INVALID_INT {
            get {
                return ResourceManager.GetString("WIN_PAGE_MAIN_INVALID_INT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter page index.
        /// </summary>
        public static string WIN_PAGE_TRANSIT_DESC {
            get {
                return ResourceManager.GetString("WIN_PAGE_TRANSIT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Pages: .
        /// </summary>
        public static string WIN_PAGE_TRANSIT_MAX_PAGE {
            get {
                return ResourceManager.GetString("WIN_PAGE_TRANSIT_MAX_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to could not fetch max page.
        /// </summary>
        public static string WIN_PAGE_TRANSIT_NULL {
            get {
                return ResourceManager.GetString("WIN_PAGE_TRANSIT_NULL", resourceCulture);
            }
        }
    }
}
